<?php
WLD_WC_ACF_Location::init();
WLD_WC_Cart::init();
WLD_WC_Cart_In_Menu::init();
WLD_WC_Checkout_Blocks::init();
WLD_WC_Fields::init();
WLD_WC_Global::init();
WLD_WC_Image_Sizes::init();
WLD_WC_My_Account::init();
WLD_WC_Quantity::init();
WLD_WC_Sidebar::init();
